# Generated by Django 5.2.17 on 2026-10-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "queue",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("hostname", models.CharField(blank=True, max_length=200)),
                ("build", models.CharField(blank=True, max_length=80)),
                ("seen_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "heartbeat worker",
                "verbose_name_plural": "heartbeat worker",
            },
        ),
    ]
