# Generated by Django 5.2.17 on 2026-09-29 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("title", models.CharField(max_length=180)),
                ("proposed_default", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aperta"),
                            ("PROPOSED", "Proposta"),
                            ("APPROVED", "Approvata"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=120)),
                ("outcome", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
    ]
