# Generated by Django 5.2.17 on 2026-10-02 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("governance", "0002_pathauditevent_commandreceipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FAMILY", "Famiglie e studenti"),
                            ("GUARDIANSHIP", "Deleghe"),
                            ("INVITE", "Inviti"),
                            ("EXPORT", "Esportazioni"),
                            ("IMPORT", "Importazioni"),
                            ("PRIVACY", "Diritti degli interessati"),
                            ("RETENTION", "Conservazione"),
                            ("ADMIN", "Amministrazione di emergenza"),
                        ],
                        max_length=16,
                    ),
                ),
                ("operation", models.CharField(max_length=60)),
                ("object_type", models.CharField(blank=True, max_length=80)),
                (
                    "object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("object_version", models.PositiveIntegerField(blank=True, null=True)),
                ("purpose", models.CharField(blank=True, max_length=120)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("command", models.CharField(blank=True, max_length=120)),
                ("correlation_id", models.UUIDField(db_index=True, default=uuid.uuid4)),
                ("details", models.JSONField(default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["category", "occurred_at"],
                        name="governance__categor_04f662_idx",
                    )
                ],
            },
        ),
    ]
