# Generated by Django 5.2.17 on 2026-10-01 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("education", "0004_teachingrequest_mode"),
        ("scheduling", "0002_planningsnapshot_environment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_key", models.CharField(max_length=100, unique=True)),
                ("kind", models.CharField(max_length=30)),
                ("payload", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CalendarResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("TUTOR", "Tutor"),
                            ("STUDENT", "Studente"),
                            ("RESOURCE", "Spazio/video"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.resource",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.student",
                    ),
                ),
                (
                    "tutor",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonOccurrence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_PERSON", "Presenza"), ("ONLINE", "Online")],
                        max_length=9,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("ON_SITE", "Sede"), ("REMOTE", "Remoto")],
                        max_length=8,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("tutor_occupied_until", models.DateTimeField()),
                ("space_occupied_until", models.DateTimeField(null=True)),
                ("video_occupied_until", models.DateTimeField(null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PUBLISHED", "Pubblicata sperimentale"),
                            ("CANCELLED", "Cancellata"),
                        ],
                        default="PUBLISHED",
                        max_length=9,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scheduling.demandunit",
                    ),
                ),
                (
                    "space",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="space_lessons",
                        to="education.resource",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.subject",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.tutor",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_lessons",
                        to="education.resource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LessonParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="lesson_calendar.lessonoccurrence",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision_after", models.PositiveBigIntegerField()),
                ("accepted_unassigned", models.JSONField(default=list)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publication",
                        to="scheduling.scheduleplan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="lessonoccurrence",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="lesson_calendar.publication",
            ),
        ),
        migrations.CreateModel(
            name="CalendarAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation", models.CharField(max_length=30)),
                ("reason", models.CharField(max_length=200)),
                ("before", models.JSONField(default=dict)),
                ("after", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lesson_calendar.lessonoccurrence",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lesson_calendar.publication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="lesson_calendar.lessonoccurrence",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lesson_calendar.calendarresource",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="calendarresource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "TUTOR"),
                        ("resource__isnull", True),
                        ("student__isnull", True),
                        ("tutor__isnull", False),
                    ),
                    models.Q(
                        ("kind", "STUDENT"),
                        ("resource__isnull", True),
                        ("student__isnull", False),
                        ("tutor__isnull", True),
                    ),
                    models.Q(
                        ("kind", "RESOURCE"),
                        ("resource__isnull", False),
                        ("student__isnull", True),
                        ("tutor__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="calendar_resource_exact_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonparticipant",
            constraint=models.UniqueConstraint(
                fields=("lesson", "student"), name="unique_lesson_student"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_at__gt", models.F("start_at")),
                    ("tutor_occupied_until__gte", models.F("end_at")),
                ),
                name="lesson_positive_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mode", "ONLINE"),
                    models.Q(
                        ("location", "ON_SITE"),
                        ("mode", "IN_PERSON"),
                        ("space__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="lesson_presence_space",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonoccurrence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "PUBLISHED")),
                fields=("demand",),
                name="one_active_lesson_per_demand",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcebooking",
            index=models.Index(
                fields=["resource", "start_at", "end_at"],
                name="lesson_cale_resourc_5b7197_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcebooking",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("start_at"))),
                name="booking_positive_interval",
            ),
        ),
        migrations.AddConstraint(
            model_name="resourcebooking",
            constraint=models.UniqueConstraint(
                fields=("lesson", "resource"), name="unique_lesson_booking"
            ),
        ),
    ]
