# Generated by Django 5.2.17 on 2026-10-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0004_teachingrequest_mode"),
        ("lesson_calendar", "0002_postgres_protection"),
        ("scheduling", "0002_planningsnapshot_environment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lessonoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("location__in", ["ON_SITE", "REMOTE"]),
                    ("mode__in", ["IN_PERSON", "ONLINE"]),
                    ("state__in", ["PUBLISHED", "CANCELLED"]),
                ),
                name="calendar_lesson_enum",
            ),
        ),
    ]
