# Generated by Django 5.2.17 on 2026-10-02 10:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0004_teachingrequest_mode"),
        ("lesson_calendar", "0003_lessonoccurrence_calendar_lesson_enum"),
        ("scheduling", "0002_planningsnapshot_environment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Presente"),
                            ("ABSENT", "Assente"),
                            ("JUSTIFIED", "Assente giustificato"),
                            ("NOT_RECORDED", "Non rilevato"),
                        ],
                        max_length=12,
                    ),
                ),
                ("minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Presente"),
                            ("ABSENT", "Assente"),
                            ("JUSTIFIED", "Assente giustificato"),
                            ("NOT_RECORDED", "Non rilevato"),
                        ],
                        max_length=12,
                    ),
                ),
                ("minutes", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("command", models.CharField(max_length=30)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CANCEL", "Cancellazione"),
                            ("RESCHEDULE", "Spostamento"),
                            ("ABSENCE", "Assenza"),
                            ("OTHER", "Altro"),
                        ],
                        max_length=12,
                    ),
                ),
                ("proposal", models.JSONField(default=dict)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("CENTER", "Centro"),
                            ("TUTOR", "Tutor"),
                            ("GUARDIAN", "Tutore legale"),
                            ("STUDENT", "Studente"),
                        ],
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Inviata"),
                            ("ACCEPTED", "Accettata"),
                            ("REJECTED", "Respinta"),
                            ("WITHDRAWN", "Ritirata"),
                        ],
                        default="SUBMITTED",
                        max_length=10,
                    ),
                ),
                (
                    "resolution_note",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ConflictCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("VALIDATION", "Lezione non più valida sui dati correnti"),
                            ("DATA_NOT_READY", "Dati della settimana non compilabili"),
                            ("STUDENT_ABSENCE", "Assenza segnalata"),
                            ("TUTOR_ABSENCE", "Assenza tutor segnalata"),
                        ],
                        max_length=24,
                    ),
                ),
                ("codes", models.JSONField(default=list)),
                ("dedupe_key", models.CharField(max_length=200)),
                ("source", models.JSONField(default=dict)),
                (
                    "state",
                    models.CharField(
                        choices=[("OPEN", "Aperta"), ("RESOLVED", "Risolta")],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CANCEL", "Lezione cancellata"),
                            ("RESCHEDULE", "Lezione spostata"),
                            ("CONFIRM", "Confermata dopo correzione del dato"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                (
                    "resolution_note",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HorizonProposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                ("revision", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Run di bozza creato"),
                            ("BLOCKED", "Bloccata da conflitti/dati"),
                            ("COVERED", "Nessuna domanda scoperta"),
                        ],
                        max_length=10,
                    ),
                ),
                ("blocking", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="LessonSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Rome", max_length=64)),
                ("start_date", models.DateField(help_text="DTSTART locale (data)")),
                ("start_time", models.TimeField(help_text="DTSTART locale (ora)")),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                ("rrule", models.CharField(max_length=200)),
                (
                    "until_date",
                    models.DateField(help_text="Ultima data locale inclusa"),
                ),
                ("exdates", models.JSONField(default=list)),
                ("overrides", models.JSONField(default=dict)),
                ("carried", models.JSONField(default=dict)),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_PERSON", "Presenza"), ("ONLINE", "Online")],
                        max_length=9,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("ON_SITE", "Sede"), ("REMOTE", "Remoto")],
                        max_length=8,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("ACTIVE", "Attiva"), ("CLOSED", "Chiusa/segmentata")],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "DRAFT"),
                            ("VALIDATED", "VALIDATED"),
                            ("PUBLISHED", "PUBLISHED"),
                            ("STALE", "STALE"),
                            ("REJECTED", "REJECTED"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "validated_revision",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("report", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryObligation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canonical_key", models.CharField(max_length=120, unique=True)),
                ("participants", models.JSONField(default=list)),
                ("minutes_remaining", models.PositiveSmallIntegerField()),
                (
                    "cause",
                    models.CharField(
                        choices=[
                            ("CENTER_CANCELLATION", "Cancellazione del centro"),
                            ("FAMILY_REQUEST", "Richiesta della famiglia"),
                            ("TUTOR_ABSENCE", "Assenza del tutor"),
                            ("STUDENT_ABSENCE", "Assenza dello studente"),
                            ("CLOSURE", "Chiusura"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("OPEN", "Da recuperare"),
                            ("SCHEDULED", "Recupero pubblicato"),
                            ("FULFILLED", "Recuperato"),
                            ("WAIVED", "Rinunciato"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="lessonoccurrence",
            name="calendar_lesson_enum",
        ),
        migrations.AddField(
            model_name="calendaraudit",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendaraudit",
            name="object_type",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="calendaraudit",
            name="system_actor",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="lessonoccurrence",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonoccurrence",
            name="recurrence_key",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="calendaraudit",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="lessonoccurrence",
            name="state",
            field=models.CharField(
                choices=[
                    ("PUBLISHED", "Pubblicata sperimentale"),
                    ("CANCELLED", "Cancellata"),
                    ("COMPLETED", "Conclusa"),
                ],
                default="PUBLISHED",
                max_length=9,
            ),
        ),
        migrations.AddConstraint(
            model_name="calendaraudit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actor__isnull", False),
                    models.Q(("system_actor", ""), _negated=True),
                    _connector="OR",
                ),
                name="calendar_audit_actor_required",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendances",
                to="lesson_calendar.lessonoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="participant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance",
                to="lesson_calendar.lessonparticipant",
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancerevision",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attendancerevision",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="lesson_calendar.attendance",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="change_requests",
                to="lesson_calendar.lessonoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="resolver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="education.student",
            ),
        ),
        migrations.AddField(
            model_name="conflictcase",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conflict_cases",
                to="lesson_calendar.lessonoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="conflictcase",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="horizonproposal",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduling.schedulerun",
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lesson_calendar.lessonseries",
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calendar_series",
                to="education.teachingrequest",
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="root",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="lesson_calendar.lessonseries",
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="space",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="education.resource",
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="education.tutor"
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="education.resource",
            ),
        ),
        migrations.AddField(
            model_name="lessonoccurrence",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lessons",
                to="lesson_calendar.lessonseries",
            ),
        ),
        migrations.AddField(
            model_name="planreview",
            name="plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review",
                to="scheduling.scheduleplan",
            ),
        ),
        migrations.AddField(
            model_name="planreview",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoveryobligation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoveryobligation",
            name="demand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="scheduling.demandunit"
            ),
        ),
        migrations.AddField(
            model_name="recoveryobligation",
            name="origin_lesson",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recovery_obligation",
                to="lesson_calendar.lessonoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="lessonoccurrence",
            name="recovery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="makeup_lessons",
                to="lesson_calendar.recoveryobligation",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("location__in", ["ON_SITE", "REMOTE"]),
                    ("mode__in", ["IN_PERSON", "ONLINE"]),
                    ("state__in", ["PUBLISHED", "CANCELLED", "COMPLETED"]),
                ),
                name="calendar_lesson_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonoccurrence",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recurrence_key__isnull", False)),
                fields=("recurrence_key",),
                name="unique_lesson_recurrence_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonoccurrence",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("recovery__isnull", False),
                    ("state__in", ["PUBLISHED", "COMPLETED"]),
                ),
                fields=("recovery",),
                name="one_active_makeup_per_obligation",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonoccurrence",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_at__isnull", False), ("state", "COMPLETED")),
                    models.Q(
                        models.Q(("state", "COMPLETED"), _negated=True),
                        ("completed_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="lesson_completed_at_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["PRESENT", "ABSENT", "JUSTIFIED", "NOT_RECORDED"])
                ),
                name="attendance_status_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minutes__isnull", True),
                    models.Q(("minutes__gt", 0), ("status", "PRESENT")),
                    _connector="OR",
                ),
                name="attendance_minutes_present_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerevision",
            constraint=models.UniqueConstraint(
                fields=("attendance", "sequence"), name="attendance_revision_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="conflictcase",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "OPEN")),
                fields=("dedupe_key",),
                name="one_open_conflict_per_key",
            ),
        ),
        migrations.AddConstraint(
            model_name="conflictcase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("resolution", ""), ("state", "OPEN")),
                    models.Q(
                        ("resolved_by__isnull", False),
                        ("state", "RESOLVED"),
                        models.Q(("resolution", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="conflict_resolution_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="horizonproposal",
            constraint=models.UniqueConstraint(
                fields=("week_start", "revision"), name="one_horizon_proposal_per_rev"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("until_date__gte", models.F("start_date"))),
                name="series_period_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("timezone", "Europe/Rome")),
                name="series_timezone_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonseries",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mode", "ONLINE"),
                    models.Q(
                        ("location", "ON_SITE"),
                        ("mode", "IN_PERSON"),
                        ("space__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="series_presence_space",
            ),
        ),
        migrations.AddConstraint(
            model_name="planreview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ["DRAFT", "VALIDATED", "PUBLISHED", "STALE", "REJECTED"],
                    )
                ),
                name="plan_review_state_enum",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(("minutes_remaining__gt", 0)),
                name="recovery_minutes_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoveryobligation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("state__in", ["OPEN", "SCHEDULED", "FULFILLED", "WAIVED"])
                ),
                name="recovery_state_enum",
            ),
        ),
    ]
