"""Modifiche di orario/durata proposte dal centro e confermate dagli interessati.

Su PostgreSQL ridefinisce calendar_assert_lesson (v3): la durata di una lezione può
differire da quella dell'unità canonica (cambio durata da Agenda), purché positiva e
al massimo 8 ore; le lezioni di recupero restano vincolate ai minuti dell'obbligo.
"""

import importlib

# Generated by Django 5.2.17 on 2026-10-04 21:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


_v2 = importlib.import_module("apps.calendar.migrations.0005_postgres_protection_v2")
V2_FUNCTION = _v2._v2_function()
OLD = "l.end_at-l.start_at<>make_interval(mins=>COALESCE(rec_minutes,(unit->>'duration_minutes')::integer)) OR"
NEW = ("(l.recovery_id IS NOT NULL AND l.end_at-l.start_at<>make_interval(mins=>rec_minutes)) OR\n"
       "    l.end_at<=l.start_at OR l.end_at-l.start_at>interval '8 hours' OR")


def v3_function():
    if OLD not in V2_FUNCTION:
        raise RuntimeError("0005 function changed: cannot derive v3")
    return V2_FUNCTION.replace(OLD, NEW, 1)


def install(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(v3_function(), params=None)


def remove(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(V2_FUNCTION, params=None)


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_request_recurring_no_total'),
        ('lesson_calendar', '0006_tutor_acknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('previous_start_at', models.DateTimeField()),
                ('previous_end_at', models.DateTimeField()),
                ('lesson_version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('APPLIED', 'APPLIED'), ('REJECTED', 'REJECTED'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], default='PENDING', max_length=9)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, default='', max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_changes', to='lesson_calendar.lessonoccurrence')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonChangeAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('party', models.CharField(choices=[('TUTOR', 'Tutor'), ('STUDENT', 'Studente')], max_length=7)),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('ACCEPTED', 'Accettata'), ('REJECTED', 'Rifiutata')], default='PENDING', max_length=8)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lesson_calendar.lessonchange')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education.student')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education.tutor')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lessonchange',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'PENDING')), fields=('lesson',), name='one_pending_change_per_lesson'),
        ),
        migrations.AddConstraint(
            model_name='lessonchange',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='lesson_change_positive_interval'),
        ),
        migrations.AddConstraint(
            model_name='lessonchangeanswer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('party', 'TUTOR'), ('student__isnull', True), ('tutor__isnull', False)), models.Q(('party', 'STUDENT'), ('student__isnull', False), ('tutor__isnull', True)), _connector='OR'), name='lesson_change_answer_party'),
        ),
        migrations.RunPython(install, remove),
    ]
