# Generated by Django 5.2.17 on 2026-10-02 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("education", "0004_teachingrequest_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FamilyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_profile",
                        to="education.family",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GuardianLinkDetail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("PARENT", "Genitore"),
                            ("LEGAL_GUARDIAN", "Tutore legale"),
                            ("DELEGATE", "Delegato autorizzato"),
                        ],
                        default="PARENT",
                        max_length=16,
                    ),
                ),
                ("can_receive_notifications", models.BooleanField(default=True)),
                ("can_request_changes", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_method", models.CharField(blank=True, max_length=120)),
                ("revocation_reason", models.CharField(blank=True, max_length=200)),
                (
                    "reconfirmation",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Non richiesta"),
                            ("PENDING", "Da riconfermare con lo studente maggiorenne"),
                            ("CONFIRMED", "Riconfermata"),
                            ("DECLINED", "Non riconfermata (revocata)"),
                        ],
                        default="NOT_REQUIRED",
                        max_length=12,
                    ),
                ),
                (
                    "reconfirmation_flagged_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("reconfirmation_due_at", models.DateTimeField(blank=True, null=True)),
                ("reconfirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "link",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="education.guardianlink",
                    ),
                ),
                (
                    "reconfirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("template_version", models.CharField(max_length=10)),
                ("file_sha256", models.CharField(max_length=64)),
                ("dry_run", models.BooleanField()),
                ("status", models.CharField(max_length=10)),
                ("rows", models.PositiveIntegerField(default=0)),
                ("summary", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=list)),
                ("minimized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Accesso (art. 15)"),
                            ("RECTIFICATION", "Rettifica (art. 16)"),
                            ("ERASURE", "Cancellazione (art. 17)"),
                            ("RESTRICTION", "Limitazione (art. 18)"),
                            ("PORTABILITY", "Portabilità (art. 20)"),
                            ("OBJECTION", "Opposizione (art. 21)"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "subject_type",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Studente"),
                            ("ACCOUNT", "Account (genitore, tutor, staff)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("subject_id", models.UUIDField(db_index=True)),
                ("subject_pseudonym", models.CharField(max_length=24)),
                ("channel", models.CharField(max_length=60)),
                ("requester_role", models.CharField(max_length=60)),
                ("received_at", models.DateTimeField()),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Ricevuta"),
                            ("VERIFIED", "Identità verificata"),
                            ("EXTENDED", "Prorogata (art. 12.3)"),
                            ("COMPLETED", "Evasa"),
                            ("REJECTED", "Respinta"),
                        ],
                        default="RECEIVED",
                        max_length=9,
                    ),
                ),
                ("identity_verified_at", models.DateTimeField(blank=True, null=True)),
                ("identity_verification", models.CharField(blank=True, max_length=200)),
                ("extension_reason", models.CharField(blank=True, max_length=200)),
                ("outcome", models.CharField(blank=True, max_length=40)),
                ("motivation", models.CharField(blank=True, max_length=500)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="ProtectedExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purpose", models.CharField(max_length=60)),
                (
                    "format",
                    models.CharField(
                        choices=[("json", "JSON"), ("csv", "CSV")], max_length=4
                    ),
                ),
                ("filename", models.CharField(max_length=120)),
                ("storage_name", models.CharField(blank=True, max_length=80)),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(max_length=64)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("downloaded_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "privacy_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="privacy.privacyrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("category", models.CharField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("purpose", models.CharField(blank=True, max_length=200)),
                ("legal_basis", models.CharField(blank=True, max_length=120)),
                ("duration_days", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DELETE", "Cancellazione"),
                            ("MINIMIZE", "Minimizzazione"),
                            ("REPORT", "Solo conteggio (nessuna azione automatica)"),
                            ("EXTERNAL", "Gestita fuori dall'applicazione"),
                        ],
                        max_length=10,
                    ),
                ),
                ("backup_note", models.CharField(blank=True, max_length=200)),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Da approvare"),
                            ("APPROVED", "Approvata"),
                            ("SUSPENDED", "Sospesa"),
                        ],
                        default="PROPOSED",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approval_reference", models.CharField(blank=True, max_length=200)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="RetentionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("dry_run", models.BooleanField(default=True)),
                ("reference_time", models.DateTimeField()),
                ("results", models.JSONField(default=list)),
                ("receipt_hash", models.CharField(blank=True, max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentImportKey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("source_key", models.CharField(max_length=80, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_key",
                        to="education.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("anonymized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_profile",
                        to="education.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "In attesa"),
                            ("ACCEPTED", "Accettato"),
                            ("REVOKED", "Revocato"),
                            ("EXPIRED", "Scaduto"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="privacy.importbatch",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="education.guardianlink",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("account",),
                        name="privacy_one_pending_invite_per_account",
                    )
                ],
            },
        ),
    ]
