# Generated by Django 5.2.17 on 2026-10-02 11:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_security_baseline"),
        ("privacy", "0002_seed_retention_matrix"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvitationTerms",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("PARENT", "Genitore"),
                            ("LEGAL_GUARDIAN", "Tutore legale"),
                            ("DELEGATE", "Delegato autorizzato"),
                        ],
                        default="PARENT",
                        max_length=16,
                    ),
                ),
                ("can_receive_notifications", models.BooleanField(default=True)),
                ("can_request_changes", models.BooleanField(default=False)),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="privacy.importbatch",
                    ),
                ),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_terms",
                        to="identity.invitation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Invitation",
        ),
    ]
