# Generated by Django 5.2.17 on 2026-10-04 15:12

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_request_approval_tutor_choice'),
        ('identity', '0004_family_guardians'),
        ('privacy', '0005_notice_acknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('relationship', models.CharField(choices=[('PARENT', 'Genitore'), ('LEGAL_GUARDIAN', 'Tutore legale'), ('DELEGATE', 'Delegato autorizzato')], default='PARENT', max_length=16)),
                ('can_manage_availability', models.BooleanField(default=True)),
                ('can_receive_notifications', models.BooleanField(default=True)),
                ('can_request_changes', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.CharField(blank=True, max_length=200)),
                ('version', models.PositiveIntegerField(default=1)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_guardianships', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='education.family')),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_guardian', to='identity.invitation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('family'), condition=models.Q(('revoked_at__isnull', True)), name='family_guardian_active_unique')],
            },
        ),
    ]
