# Generated by Django 5.2.17 on 2026-09-29 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailabilityRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(help_text="0=lunedì, 6=domenica"),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("timezone", models.CharField(default="Europe/Rome", max_length=64)),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_PERSON", "Presenza"), ("ONLINE", "Online")],
                        max_length=9,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("ON_SITE", "Sede"), ("REMOTE", "Remoto")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Bozza"),
                            ("APPROVED", "Approvata"),
                            ("REVOKED", "Revocata"),
                        ],
                        default="DRAFT",
                        max_length=8,
                    ),
                ),
            ],
        ),
    ]
