# Generated by Django 5.2.17 on 2026-09-29 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("availability", "0001_initial"),
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityrule",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="availabilityrule",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="education.student",
            ),
        ),
        migrations.AddField(
            model_name="availabilityrule",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="education.tutor",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("student__isnull", True), ("tutor__isnull", False)),
                    models.Q(("student__isnull", False), ("tutor__isnull", True)),
                    _connector="OR",
                ),
                name="availability_subject_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekday__lte", 6)), name="availability_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="availability_time_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="availability_date_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="availabilityrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("mode", "ONLINE"),
                    models.Q(("location", "ON_SITE"), ("mode", "IN_PERSON")),
                    _connector="OR",
                ),
                name="availability_mode_location",
            ),
        ),
    ]
