# Generated by Django 5.2.17 on 2026-09-30 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("availability", "0002_initial"),
        ("education", "0004_teachingrequest_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="availabilityrule",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_availability_rules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AvailabilityConflict",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("reason", models.CharField(max_length=160)),
                ("open", models.BooleanField()),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.student",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.tutor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("student__isnull", True), ("tutor__isnull", False)
                            ),
                            models.Q(
                                ("student__isnull", False), ("tutor__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="availability_conflict_xor",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityDeclaration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Dati approvati"),
                            ("DECLARED_NONE", "Nessuna disponibilità"),
                            ("UNKNOWN", "Dati incompleti"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.student",
                    ),
                ),
                (
                    "tutor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.tutor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("student__isnull", True), ("tutor__isnull", False)
                            ),
                            models.Q(
                                ("student__isnull", False), ("tutor__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="availability_declaration_xor",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AvailabilityException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_PERSON", "Presenza"), ("ONLINE", "Online")],
                        max_length=9,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("ON_SITE", "Sede"), ("REMOTE", "Remoto")],
                        max_length=8,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ADD_AVAILABLE", "Aggiunta"),
                            ("REMOVE_AVAILABLE", "Rimozione"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.student",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.tutor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("student__isnull", True), ("tutor__isnull", False)
                            ),
                            models.Q(
                                ("student__isnull", False), ("tutor__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="availability_exception_xor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="exception_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("mode", "ONLINE"),
                            models.Q(("location", "ON_SITE"), ("mode", "IN_PERSON")),
                            _connector="OR",
                        ),
                        name="exception_location",
                    ),
                ],
            },
        ),
    ]
