# Generated by Django 5.2.17 on 2026-09-29 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("education", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="guardianlink",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardian_links",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("kind", "SPACE"),
                        ("student_capacity__gte", 1),
                        ("student_capacity__isnull", False),
                    ),
                    models.Q(
                        ("kind", "VIDEO_CHANNEL"), ("student_capacity__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="resource_capacity_by_kind",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="education.family"
            ),
        ),
        migrations.AddField(
            model_name="guardianlink",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guardian_links",
                to="education.student",
            ),
        ),
        migrations.AddField(
            model_name="teachingrequest",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="education.student"
            ),
        ),
        migrations.AddField(
            model_name="teachingrequest",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="education.subject"
            ),
        ),
        migrations.AddField(
            model_name="tutor",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tutor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="guardianlink",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_until__isnull", True),
                    ("valid_until__gt", models.F("valid_from")),
                    _connector="OR",
                ),
                name="guardian_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="request_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("sessions_per_week__gte", 1)),
                name="request_positive_sessions",
            ),
        ),
    ]
