# Generated by Django 5.2.17 on 2026-09-29 23:07

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingrequest",
            name="source_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="teachingrequest",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="education.student",
            ),
        ),
        migrations.CreateModel(
            name="CurriculumBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("objective", models.CharField(max_length=300)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("minutes_per_week", models.PositiveIntegerField()),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(
                        choices=[(60, "60"), (90, "90"), (120, "120")]
                    ),
                ),
                ("sessions_per_week", models.PositiveSmallIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_PERSON", "Presenza"), ("ONLINE", "Online")],
                        max_length=9,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("P0", "P0"), ("P1", "P1"), ("P2", "P2")], max_length=2
                    ),
                ),
                ("mandatory", models.BooleanField()),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teachingrequest",
            name="curriculum_block",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_request",
                to="education.curriculumblock",
            ),
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=140)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("HOME_EDUCATION", "Programma scolastico completo"),
                            ("TUTORING", "Ripetizioni"),
                        ],
                        max_length=20,
                    ),
                ),
                ("academic_year", models.CharField(max_length=30)),
                ("level", models.CharField(max_length=80)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("curriculum_version", models.PositiveIntegerField(default=1)),
                (
                    "required_subjects",
                    models.ManyToManyField(
                        related_name="learning_paths", to="education.subject"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curriculumblock",
            name="path",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="blocks",
                to="education.learningpath",
            ),
        ),
        migrations.CreateModel(
            name="PathEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("active", models.BooleanField(default=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="enrollments",
                        to="education.learningpath",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="path_enrollments",
                        to="education.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RequestParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="education.teachingrequest",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeachingGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=100)),
                (
                    "online_capacity",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("approved", models.BooleanField(default=False)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="groups",
                        to="education.learningpath",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.student",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="education.teachinggroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="curriculumblock",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="education.teachinggroup",
            ),
        ),
        migrations.AddField(
            model_name="teachingrequest",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="education.teachinggroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="teachingrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", True), ("student__isnull", False)),
                    models.Q(("group__isnull", False), ("student__isnull", True)),
                    _connector="OR",
                ),
                name="request_target_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="learningpath",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="path_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="pathenrollment",
            constraint=models.UniqueConstraint(
                fields=("path", "student"), name="path_student_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="pathenrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="enrollment_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="requestparticipant",
            constraint=models.UniqueConstraint(
                fields=("request", "student"), name="request_participant_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="teachinggroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("online_capacity__isnull", True),
                    ("online_capacity__gte", 2),
                    _connector="OR",
                ),
                name="group_online_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.UniqueConstraint(
                fields=("group", "student"), name="group_student_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmembership",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="membership_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("group__isnull", True), ("student__isnull", False)),
                    models.Q(("group__isnull", False), ("student__isnull", True)),
                    _connector="OR",
                ),
                name="curriculum_target_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="curriculum_valid_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumblock",
            constraint=models.CheckConstraint(
                condition=models.Q(("sessions_per_week__gte", 1)),
                name="curriculum_positive_sessions",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumblock",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "minutes_per_week",
                        django.db.models.expressions.CombinedExpression(
                            models.F("duration_minutes"),
                            "*",
                            models.F("sessions_per_week"),
                        ),
                    )
                ),
                name="curriculum_minutes_match",
            ),
        ),
    ]
