# Generated by Django 5.2.17 on 2026-09-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0003_teachingrequest_source_fingerprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingrequest",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[("IN_PERSON", "Presenza"), ("ONLINE", "Online")],
                max_length=9,
            ),
        ),
    ]
