# Generated by Django 5.2.17 on 2026-10-04 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_tutor_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingrequest',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='origin',
            field=models.CharField(choices=[('CENTER', 'Centro'), ('GUARDIAN', 'Famiglia')], default='CENTER', max_length=8),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='preferred_tutors',
            field=models.ManyToManyField(blank=True, related_name='preferred_in_requests', to='education.tutor'),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='review_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Da approvare'), ('APPROVED', 'Approvata'), ('REJECTED', 'Rifiutata'), ('WITHDRAWN', 'Ritirata')], default='APPROVED', max_length=10),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='tutor_choice',
            field=models.CharField(choices=[('ANY', 'Qualsiasi tutor competente'), ('PREFERRED', 'Tutor preferito'), ('REQUIRED', 'Tutor obbligatorio')], default='ANY', max_length=9),
        ),
    ]
