# Generated by Django 5.2.17 on 2026-10-04 16:33

from django.conf import settings
from django.db import migrations, models


def portal_channel(apps, schema_editor):
    # Le richieste già inviate dalle famiglie sono arrivate dal portale.
    TeachingRequest = apps.get_model("education", "TeachingRequest")
    TeachingRequest.objects.filter(origin="GUARDIAN").update(channel="PORTAL")


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_request_approval_tutor_choice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='channel',
            field=models.CharField(choices=[('PORTAL', 'Portale famiglie'), ('PHONE', 'Telefono'), ('EMAIL', 'Email'), ('IN_PERSON', 'Di persona'), ('MESSAGE', 'Messaggio'), ('INTERNAL', 'Iniziativa del centro')], default='INTERNAL', max_length=9),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='fixed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='kind',
            field=models.CharField(choices=[('SINGLE', 'Lezione singola'), ('SERIES', 'Percorso di lezioni'), ('WEEKLY', 'Settimanale sul periodo')], default='WEEKLY', max_length=6),
        ),
        migrations.AddField(
            model_name='teachingrequest',
            name='total_lessons',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='teachingrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'SERIES'), _negated=True), ('total_lessons__gte', 1), _connector='OR'), name='request_series_total'),
        ),
        migrations.AddConstraint(
            model_name='teachingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('fixed_time__isnull', True), models.Q(('kind', 'SINGLE'), ('period_end', models.F('period_start'))), _connector='OR'), name='request_fixed_time_single_day'),
        ),
        migrations.RunPython(portal_channel, migrations.RunPython.noop),
    ]
