# Generated by Django 5.2.17 on 2026-10-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_request_kinds_subject_page'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teachingrequest',
            name='request_series_total',
        ),
        migrations.RemoveField(
            model_name='teachingrequest',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='teachingrequest',
            name='total_lessons',
        ),
        migrations.AlterField(
            model_name='teachingrequest',
            name='kind',
            field=models.CharField(choices=[('SINGLE', 'Lezione singola'), ('SERIES', 'Ricorrente con lo stesso tutor'), ('WEEKLY', 'Settimanale sul periodo')], default='WEEKLY', max_length=6),
        ),
    ]
