# Generated by Django 5.2.17 on 2026-10-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0008_request_recurring_no_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachingrequest",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teachingrequest",
            name="group_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="teachingrequest",
            name="planning_state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non pianificata"),
                    ("REVIEW", "Da verificare"),
                    ("DONE", "Completata"),
                ],
                default="",
                max_length=6,
            ),
        ),
    ]
