# Generated by Django 5.2.17 on 2026-10-02 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("education", "0004_teachingrequest_mode"),
        ("lesson_calendar", "0003_lessonoccurrence_calendar_lesson_enum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarFeedToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=60)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Servizio"),
                            ("MARKETING", "Promozionale"),
                        ],
                        default="SERVICE",
                        max_length=10,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=200, unique=True)),
                ("payload_hash", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "subject_ref",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("category__in", ["SERVICE", "MARKETING"])),
                        name="outbox_category_enum",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "Notifica nel portale"),
                            ("EMAIL", "Email"),
                        ],
                        max_length=8,
                    ),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "In attesa"),
                            ("SENDING", "In invio"),
                            ("SENT", "Consegnata al canale"),
                            ("AMBIGUOUS", "Esito ambiguo: in riconciliazione"),
                            ("DEAD", "Dead-letter: da verificare"),
                            ("SKIPPED", "Non inviata (preferenze o recapito assente)"),
                            ("CANCELLED", "Annullata dal centro"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField()),
                ("lease_until", models.DateTimeField(blank=True, null=True)),
                ("enqueued_at", models.DateTimeField(blank=True, null=True)),
                ("provider", models.CharField(blank=True, max_length=20)),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                ("last_error_code", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="communications.outboxevent",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChannelPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Servizio"),
                            ("MARKETING", "Promozionale"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "Notifica nel portale"),
                            ("EMAIL", "Email"),
                        ],
                        max_length=8,
                    ),
                ),
                ("enabled", models.BooleanField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "category", "channel"),
                        name="preference_account_category_channel_uq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeliveryAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveSmallIntegerField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Accettata"),
                            ("DUPLICATE_SUPPRESSED", "Duplicato soppresso"),
                            ("TRANSIENT_ERROR", "Errore temporaneo"),
                            ("PERMANENT_ERROR", "Errore permanente"),
                            ("AMBIGUOUS", "Esito ambiguo"),
                            ("LEASE_EXPIRED", "Worker interrotto durante l'invio"),
                            ("RECONCILED_SENT", "Riconciliata: accettata dal provider"),
                            ("RECONCILED_NOT_FOUND", "Riconciliata: non ricevuta"),
                            ("RECONCILED_UNKNOWN", "Riconciliazione non conclusiva"),
                            ("SKIPPED", "Non inviata"),
                            ("MANUAL", "Decisione manuale del centro"),
                        ],
                        max_length=24,
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=60)),
                ("provider_message_id", models.CharField(blank=True, max_length=200)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempt_log",
                        to="communications.delivery",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["delivery", "created_at"],
                        name="communicati_deliver_6e6a11_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("join_url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="lesson_calendar.lessonoccurrence",
                    ),
                ),
                (
                    "resource",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="education.resource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("lesson__isnull", False), ("resource__isnull", True)
                            ),
                            models.Q(
                                ("lesson__isnull", True), ("resource__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="meeting_link_exactly_one_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("join_url__startswith", "https://")),
                        name="meeting_link_https",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Servizio"),
                            ("MARKETING", "Promozionale"),
                        ],
                        max_length=10,
                    ),
                ),
                ("kind", models.CharField(max_length=60)),
                ("title", models.CharField(max_length=160)),
                ("body", models.CharField(max_length=500)),
                ("subject_ref", models.CharField(blank=True, max_length=100)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="communications.outboxevent",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["recipient", "read_at", "created_at"],
                        name="communicati_recipie_a56788_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "recipient"),
                        name="notification_event_recipient_uq",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(
                fields=["status", "next_attempt_at"],
                name="communicati_status_079ef9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="delivery",
            constraint=models.UniqueConstraint(
                fields=("event", "recipient", "channel"),
                name="delivery_event_recipient_channel_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="delivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING",
                            "SENDING",
                            "SENT",
                            "AMBIGUOUS",
                            "DEAD",
                            "SKIPPED",
                            "CANCELLED",
                        ],
                    ),
                    ("channel__in", ["IN_APP", "EMAIL"]),
                ),
                name="delivery_enums",
            ),
        ),
    ]
