# Generated by Django 5.2.17 on 2026-10-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SealedSecret",
            fields=[
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sealed",
                        serialize=False,
                        to="communications.delivery",
                    ),
                ),
                ("ciphertext", models.TextField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="delivery",
            name="delivery_enums",
        ),
        migrations.AddField(
            model_name="delivery",
            name="address",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="audience",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="essential",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outboxevent",
            name="sealed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "In attesa"),
                    ("SENDING", "In invio"),
                    ("SENT", "Consegnata al canale"),
                    ("AMBIGUOUS", "Esito ambiguo: in riconciliazione"),
                    ("DEAD", "Dead-letter: da verificare"),
                    ("SKIPPED", "Non inviata (preferenze o recapito assente)"),
                    ("CANCELLED", "Annullata dal centro"),
                    ("REVOKED", "Annullata: destinatario non più autorizzato"),
                    ("EXPIRED", "Annullata: contenuto riservato scaduto"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryattempt",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("ACCEPTED", "Accettata"),
                    ("DUPLICATE_SUPPRESSED", "Duplicato soppresso"),
                    ("TRANSIENT_ERROR", "Errore temporaneo"),
                    ("PERMANENT_ERROR", "Errore permanente"),
                    ("AMBIGUOUS", "Esito ambiguo"),
                    ("LEASE_EXPIRED", "Worker interrotto durante l'invio"),
                    ("RECONCILED_SENT", "Riconciliata: accettata dal provider"),
                    ("RECONCILED_NOT_FOUND", "Riconciliata: non ricevuta"),
                    ("RECONCILED_UNKNOWN", "Riconciliazione non conclusiva"),
                    ("SKIPPED", "Non inviata"),
                    ("REVOKED", "Destinatario non più autorizzato"),
                    ("EXPIRED", "Contenuto riservato scaduto o non disponibile"),
                    ("MANUAL", "Decisione manuale del centro"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="delivery",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recipient__isnull", True)),
                fields=("event", "address", "channel"),
                name="delivery_event_address_channel_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="delivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("recipient__isnull", False),
                    models.Q(
                        models.Q(("address", ""), _negated=True), ("channel", "EMAIL")
                    ),
                    _connector="OR",
                ),
                name="delivery_has_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="delivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING",
                            "SENDING",
                            "SENT",
                            "AMBIGUOUS",
                            "DEAD",
                            "SKIPPED",
                            "CANCELLED",
                            "REVOKED",
                            "EXPIRED",
                        ],
                    ),
                    ("channel__in", ["IN_APP", "EMAIL"]),
                ),
                name="delivery_enums",
            ),
        ),
    ]
