# Generated by Django 5.2.17 on 2026-10-05 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_delivery_address_sealed_audience'),
        ('lesson_calendar', '0007_lesson_time_change'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('CENTER', 'Centro'), ('TUTOR', 'Tutor'), ('GUARDIAN', 'Tutore legale'), ('STUDENT', 'Studente')], max_length=8)),
                ('student_ids', models.JSONField(default=list)),
                ('first_joined_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('seconds', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='lesson_calendar.lessonoccurrence')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lesson', 'account'), name='unique_meeting_presence')],
            },
        ),
    ]
