# Generated by Django 5.2.17 on 2026-09-30 19:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("education", "0004_teachingrequest_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningRevision",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("revision", models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("RUNNING", "RUNNING"),
                            ("SUCCEEDED", "SUCCEEDED"),
                            ("FAILED", "FAILED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("phase", models.CharField(default="QUEUED", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                ("claim_token", models.UUIDField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("cancel_requested", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=60)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("operation", models.CharField(max_length=60)),
                ("object_id", models.UUIDField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=120)),
                ("budget_seconds", models.FloatField()),
                ("online_onsite_requires_space", models.BooleanField()),
                ("video_channels_required", models.BooleanField()),
                (
                    "partial_week_rule",
                    models.CharField(
                        choices=[
                            ("BLOCK", "Blocca settimana parziale"),
                            (
                                "INCLUDE_ACTIVE_DATES",
                                "Quantità piena entro date attive",
                            ),
                        ],
                        max_length=30,
                    ),
                ),
                ("unsupported_constraints", models.JSONField()),
                ("approved_for_exploration", models.BooleanField()),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("budget_seconds__gte", 0.1), ("budget_seconds__lte", 10)
                        ),
                        name="planning_budget_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanningSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("revision", models.PositiveBigIntegerField()),
                ("schema_version", models.CharField(max_length=8)),
                ("horizon_start", models.DateField()),
                ("horizon_end", models.DateField()),
                ("policy_version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
                ("input_hash", models.CharField(max_length=64)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="scheduling.planningpolicy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceTiming",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("buffer_minutes", models.PositiveSmallIntegerField()),
                ("inherit_service_windows", models.BooleanField()),
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.resource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RunDispatch",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="dispatch",
                        serialize=False,
                        to="scheduling.schedulerun",
                    ),
                ),
                ("status", models.CharField(default="PENDING", max_length=10)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name="schedulerun",
            name="snapshot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduling.planningsnapshot",
            ),
        ),
        migrations.CreateModel(
            name="SchedulePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("VALIDATED", "Validata sullo snapshot"),
                            ("STALE", "Obsoleta"),
                        ],
                        max_length=12,
                    ),
                ),
                ("assignments", models.JSONField()),
                ("result_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan",
                        to="scheduling.schedulerun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Closure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ALL", "Tutte"),
                            ("IN_PERSON", "Presenza"),
                            ("ONLINE", "Online"),
                        ],
                        max_length=9,
                    ),
                ),
                ("reason", models.CharField(max_length=160)),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.resource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_at__gt", models.F("start_at"))),
                        name="closure_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DemandUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                ("serial", models.PositiveSmallIntegerField()),
                ("demand_key", models.CharField(max_length=80, unique=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.teachingrequest",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request", "week_start", "serial"),
                        name="canonical_request_week_serial",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceWindow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_PERSON", "Presenza"), ("ONLINE", "Online")],
                        max_length=9,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[("ON_SITE", "Sede"), ("REMOTE", "Remoto")],
                        max_length=8,
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.resource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_time__gt", models.F("start_time")),
                            ("period_end__gte", models.F("period_start")),
                            ("weekday__lte", 6),
                        ),
                        name="service_interval",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("mode", "ONLINE"),
                            models.Q(("location", "ON_SITE"), ("mode", "IN_PERSON")),
                            _connector="OR",
                        ),
                        name="service_location",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TutorOperatingPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("daily_limit_minutes", models.PositiveIntegerField()),
                ("weekly_limit_minutes", models.PositiveIntegerField()),
                ("pause_minutes", models.PositiveSmallIntegerField()),
                ("site_to_remote_minutes", models.PositiveSmallIntegerField()),
                ("remote_to_site_minutes", models.PositiveSmallIntegerField()),
                (
                    "tutor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.tutor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("daily_limit_minutes__gt", 0),
                            ("weekly_limit_minutes__gt", 0),
                        ),
                        name="tutor_positive_work_limits",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TutorSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("level", models.CharField(max_length=80)),
                (
                    "mode",
                    models.CharField(
                        choices=[("IN_PERSON", "Presenza"), ("ONLINE", "Online")],
                        max_length=9,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField()),
                ("approved", models.BooleanField(default=False)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.subject",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="education.tutor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__gte", models.F("valid_from"))
                        ),
                        name="skill_dates",
                    )
                ],
            },
        ),
    ]
