# Generated by Django 5.2.17 on 2026-09-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planningsnapshot",
            name="environment",
            field=models.JSONField(default=dict),
        ),
    ]
