# Generated by Django 5.2.17 on 2026-10-02 19:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0004_teachingrequest_mode"),
        ("scheduling", "0002_planningsnapshot_environment"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("serial", models.PositiveSmallIntegerField()),
                ("weekday", models.PositiveSmallIntegerField()),
                ("local_start_time", models.TimeField()),
                (
                    "stability",
                    models.CharField(
                        choices=[
                            ("PREFERRED", "Preferito"),
                            ("REQUIRED", "Obbligatorio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PREVIOUS_PLAN", "Proposta precedente"),
                            ("DECLARED", "Dichiarato dal centro"),
                        ],
                        max_length=14,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="planningpolicy",
            name="planning_budget_range",
        ),
        migrations.AddField(
            model_name="planningpolicy",
            name="allow_cross_local_midnight",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planningpolicy",
            name="fairness_policy_id",
            field=models.CharField(default="fairness-default", max_length=80),
        ),
        migrations.AddField(
            model_name="planningpolicy",
            name="fairness_policy_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="planningpolicy",
            name="horizon_weeks",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="planningpolicy",
            name="objective_order",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="planningpolicy",
            name="recurring_stability",
            field=models.CharField(
                choices=[
                    ("NONE", "Nessuna serie implicita"),
                    ("PREFERRED", "Slot ricorrente preferito"),
                ],
                default="NONE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="planningpolicy",
            name="student_buffer_minutes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="planningpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("budget_seconds__gte", 0.1), ("budget_seconds__lte", 30)
                ),
                name="planning_budget_range_v05",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("horizon_weeks__gte", 1), ("horizon_weeks__lte", 6)
                ),
                name="planning_horizon_weeks",
            ),
        ),
        migrations.AddConstraint(
            model_name="planningpolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("student_buffer_minutes__lte", 120)),
                name="planning_student_buffer",
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planning_slot_series",
                to="education.teachingrequest",
            ),
        ),
        migrations.AddField(
            model_name="lessonseries",
            name="source_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="scheduling.scheduleplan",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonseries",
            constraint=models.UniqueConstraint(
                fields=("request", "serial"), name="lesson_series_request_serial"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessonseries",
            constraint=models.CheckConstraint(
                condition=models.Q(("serial__gte", 1), ("weekday__lte", 6)),
                name="lesson_series_slot",
            ),
        ),
    ]
