# Generated by Django 5.2.17 on 2026-10-04 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_request_recurring_no_total'),
        ('lesson_calendar', '0006_tutor_acknowledgement'),
        ('scheduling', '0004_school_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('month', models.DateField(help_text='Primo giorno del mese')),
                ('state', models.CharField(choices=[('DRAFT', 'Bozza'), ('PUBLISHED', 'Pubblicato'), ('DISCARDED', 'Scartato')], default='DRAFT', max_length=9)),
                ('solver_status', models.CharField(blank=True, max_length=20)),
                ('stats', models.JSONField(default=dict)),
                ('unplaced', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoPlanLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(max_length=9)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('participants', models.JSONField(default=list)),
                ('overflow_minutes', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('PROPOSED', 'Proposta'), ('AWAITING', 'In attesa di conferma'), ('PUBLISHED', 'Pubblicata'), ('REJECTED', 'Rifiutata'), ('DISCARDED', 'Scartata')], default='PROPOSED', max_length=9)),
                ('occurrence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autoplan_lesson', to='lesson_calendar.lessonoccurrence')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='scheduling.autoplan')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.teachingrequest')),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='education.resource')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.subject')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='education.tutor')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoPlanConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('party', models.CharField(choices=[('STUDENT', 'Studente/famiglia'), ('TUTOR', 'Tutor')], max_length=7)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('labels', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Non ancora inviata'), ('PENDING', 'In attesa'), ('ACCEPTED', 'Accettata'), ('REJECTED', 'Rifiutata')], default='DRAFT', max_length=8)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.student')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.tutor')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='scheduling.autoplanlesson')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('weekday', models.PositiveSmallIntegerField(help_text='0=lunedì, 6=domenica')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['weekday', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='opening_weekday'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='opening_positive')],
            },
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('label', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('WEEKLY', 'Ogni settimana'), ('ONE_OFF', 'Una volta')], default='WEEKLY', max_length=7)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='education.student')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='education.tutor')),
            ],
            options={
                'ordering': ['kind', 'weekday', 'date', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', True), ('tutor__isnull', False)), models.Q(('student__isnull', False), ('tutor__isnull', True)), _connector='OR'), name='commitment_owner_xor'), models.CheckConstraint(condition=models.Q(models.Q(('date__isnull', True), ('kind', 'WEEKLY'), ('weekday__lte', 6)), models.Q(('date__isnull', False), ('kind', 'ONE_OFF'), ('weekday__isnull', True)), _connector='OR'), name='commitment_kind_fields'), models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='commitment_positive')],
            },
        ),
    ]
