# Generated by Django 5.2.17 on 2026-10-05 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0009_request_review"),
        ("scheduling", "0005_autoplanner"),
    ]

    operations = [
        migrations.AddField(
            model_name="autoplan",
            name="request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="request_plans",
                to="education.teachingrequest",
            ),
        ),
    ]
