# Generated by Django 5.2.17 on 2026-10-05 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def one_public_calendar(apps, schema_editor):
    """Un solo calendario pubblico per mese: le lezioni pubblicate da più bozze (mensili o
    di singole richieste) confluiscono nel calendario mensile più vecchio del mese."""
    AutoPlan = apps.get_model("scheduling", "AutoPlan")
    AutoPlanLesson = apps.get_model("scheduling", "AutoPlanLesson")
    months = AutoPlan.objects.filter(state="PUBLISHED").values_list("month", flat=True).distinct()
    for month in list(months):
        plans = list(AutoPlan.objects.filter(state="PUBLISHED", month=month).order_by("published_at", "created_at"))
        monthly = [p for p in plans if p.request_id is None]
        if monthly:
            target = monthly[0]
        else:
            first = plans[0]
            target = AutoPlan.objects.create(
                month=month, state="PUBLISHED", actor_id=first.actor_id, solver_status="MERGED",
                stats={"container": True}, unplaced=[], published_at=first.published_at,
            )
        for p in plans:
            if p.pk == target.pk:
                continue
            AutoPlanLesson.objects.filter(plan=p).update(plan=target)
            p.state = "MERGED"
            p.stats = {**(p.stats or {}), "merged_into": str(target.pk)}
            p.save(update_fields=["state", "stats"])


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_calendar', '0007_lesson_time_change'),
        ('scheduling', '0006_request_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoplan',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Bozza'), ('PUBLISHED', 'Pubblicato'), ('DISCARDED', 'Scartato'), ('MERGED', 'Unito al calendario del mese')], default='DRAFT', max_length=9),
        ),
        migrations.CreateModel(
            name='CalendarCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('month', models.DateField(help_text='Primo giorno del mese')),
                ('op', models.CharField(choices=[('reschedule', 'Sposta o cambia durata'), ('cancel', 'Cancella'), ('modify', 'Modifica (tutor, modalità, aula)'), ('swap', 'Scambia due lezioni'), ('plan', 'Aggiungi le lezioni di una richiesta')], max_length=10)),
                ('command', models.JSONField(default=dict)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('state', models.CharField(choices=[('PENDING', 'In bozza'), ('APPLIED', 'Pubblicata'), ('FAILED', 'Non applicabile'), ('DISCARDED', 'Scartata')], default='PENDING', max_length=9)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='lesson_calendar.lessonoccurrence')),
                ('other', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='lesson_calendar.lessonoccurrence')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='scheduling.autoplan')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['month', 'state'], name='correction_month_state')],
            },
        ),
        migrations.RunPython(one_public_calendar, migrations.RunPython.noop),
]
