# Generated by Django 5.2.17 on 2026-09-30 19:35

import apps.identity.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", apps.identity.models.AccountManager()),
            ],
        ),
    ]
