# Generated by Django 5.2.17 on 2026-10-02 10:30

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def normalize_emails(apps, schema_editor):
    """Normalizza le email esistenti (NFC, trim, minuscolo) prima del vincolo case-insensitive."""
    import unicodedata

    Account = apps.get_model("identity", "Account")
    seen = {}
    for pk, email in Account.objects.values_list("pk", "email"):
        normalized = unicodedata.normalize("NFC", email or "").strip().lower()
        if normalized in seen:
            raise RuntimeError(
                "Email duplicate ignorando maiuscole: unire gli account "
                f"{seen[normalized]} e {pk} prima della migrazione"
            )
        seen[normalized] = pk
        if normalized != email:
            Account.objects.filter(pk=pk).update(email=normalized)


# TRUNCATE non è bloccato: lo usa il flush dei test; in produzione il ruolo runtime
# non deve avere il privilegio TRUNCATE (ruoli separati, tec4).
AUDIT_SQL = """
CREATE OR REPLACE FUNCTION identity_audit_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'identity audit is append-only' USING ERRCODE = '23514';
END $$;
CREATE TRIGGER identity_audit_no_update BEFORE UPDATE OR DELETE ON identity_identityauditevent
FOR EACH ROW EXECUTE FUNCTION identity_audit_append_only();
"""
AUDIT_REVERSE = """
DROP TRIGGER IF EXISTS identity_audit_no_update ON identity_identityauditevent;
DROP FUNCTION IF EXISTS identity_audit_append_only();
"""


def install_audit_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(AUDIT_SQL, params=None)


def remove_audit_guard(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(AUDIT_REVERSE, params=None)


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("education", "0004_teachingrequest_mode"),
        ("identity", "0002_alter_account_managers"),
    ]

    operations = [
        migrations.RunPython(normalize_emails, migrations.RunPython.noop),
        migrations.CreateModel(
            name="IdentityAuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("operation", models.CharField(db_index=True, max_length=60)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["occurred_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CENTER", "Centro"),
                            ("TUTOR", "Tutor"),
                            ("GUARDIAN", "Tutore"),
                            ("STUDENT", "Studente"),
                        ],
                        max_length=12,
                    ),
                ),
                ("can_manage_availability", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_VERIFICATION", "Relazione da verificare"),
                            ("SENT", "Inviato"),
                            ("ACCEPTED", "Accettato"),
                            ("REVOKED", "Revocato"),
                        ],
                        default="PENDING_VERIFICATION",
                        max_length=24,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("send_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("relation_verified_at", models.DateTimeField(blank=True, null=True)),
                ("relation_evidence", models.CharField(blank=True, max_length=200)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="PasswordResetToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecoveryCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentAccessPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adult_confirmed", models.BooleanField(default=False)),
                (
                    "guardian_access",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default configurato"),
                            ("KEEP", "Mantieni le deleghe esistenti"),
                            ("CONSENT_REQUIRED", "Solo con consenso dello studente"),
                            ("NONE", "Nessun accesso dei tutori"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                ("student_consent_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="TOTPDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_step", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField()),
                ("mfa_verified_at", models.DateTimeField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=200)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_reason", models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="mfa_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="account_email_ci_unique",
            ),
        ),
        migrations.AddField(
            model_name="identityauditevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identity_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="identityauditevent",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identity_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="accepted_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations_accepted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="relation_verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitation_relations_verified",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invitations",
                to="education.student",
            ),
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="password_reset_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recoverycode",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recovery_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentaccesspolicy",
            name="confirmed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_policies_confirmed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="studentaccesspolicy",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="access_policy",
                to="education.student",
            ),
        ),
        migrations.AddField(
            model_name="totpdevice",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="totp_device",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role__in", ["GUARDIAN", "STUDENT"]), _negated=True),
                    ("student__isnull", False),
                    _connector="OR",
                ),
                name="invitation_student_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "GUARDIAN"), _negated=True),
                    ("token_hash__isnull", True),
                    ("relation_verified_at__isnull", False),
                    _connector="OR",
                ),
                name="invitation_guardian_verified_before_token",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("token_hash__isnull", True),
                    ("expires_at__isnull", False),
                    _connector="OR",
                ),
                name="invitation_token_expires",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                models.F("role"),
                models.F("student"),
                condition=models.Q(
                    ("status__in", ["PENDING_VERIFICATION", "SENT"]),
                    ("student__isnull", False),
                ),
                name="invitation_open_unique_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                models.F("role"),
                condition=models.Q(
                    ("status__in", ["PENDING_VERIFICATION", "SENT"]),
                    ("student__isnull", True),
                ),
                name="invitation_open_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="recoverycode",
            constraint=models.UniqueConstraint(
                fields=("account", "code_hash"), name="recovery_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["account", "revoked_at"], name="identity_us_account_3f53cc_idx"
            ),
        ),
        migrations.RunPython(install_audit_guard, remove_audit_guard),
    ]
