# Generated by Django 5.2.17 on 2026-10-04 15:12

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_request_approval_tutor_choice'),
        ('identity', '0003_security_baseline'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='invitation_student_required',
        ),
        migrations.RemoveConstraint(
            model_name='invitation',
            name='invitation_open_unique',
        ),
        migrations.AddField(
            model_name='invitation',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='education.family'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='qr_token_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role__in', ['GUARDIAN', 'STUDENT']), _negated=True), ('student__isnull', False), models.Q(('family__isnull', False), ('role', 'GUARDIAN')), _connector='OR'), name='invitation_student_required'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('role'), condition=models.Q(('family__isnull', True), ('status__in', ['PENDING_VERIFICATION', 'SENT']), ('student__isnull', True)), name='invitation_open_unique'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('role'), models.F('family'), condition=models.Q(('family__isnull', False), ('status__in', ['PENDING_VERIFICATION', 'SENT'])), name='invitation_open_unique_family'),
        ),
    ]
